### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by karl-police** [chrisjp/tts#2]
Hm, the page is down, do you want to github.io it as a page? Would that work?

**Comment by chrisjp** [comment]
Yeah I let that domain expire today. I've updated the link to go to https://lazypy.ro/tts which is where the domain was pointing to anyway. Will update the readme later.

Unfortunately github.io won't work as it doesn't support any kind of server-side scripting. Most of the TTS services on the site rely on going through my proxy.php script to handle their respective requests.
