### ISSUE TITLE
Acapela voices have a new background noise

### ISSUE THREAD

**Issue by WaleedAnimate2020** [chrisjp/tts#20]
When I tried to generate the voices, I can hear a new background noises where people talking in when the voices play after the previous API is no longer working on Acapela Downloader

**Comment by chrisjp** [comment]
Apologies for not responding sooner. I'm afraid neither of these issues are something that I can help with.
1. I have no control over whether or not Acapela adds background noise to generated TTS audio. We use their demo site so it is understandable they add limitations to it to prevent commercial use.
2. I assume by Acapela Downloader you are referring to https://github.com/weespin/WillFromAfarDownloader? That software has nothing to do with me and it looks like the person responsible has archived the repository indicating it is no longer being worked on. Therefore I wouldn't expect any fixes for that unless someone else takes over development.
