### ISSUE TITLE
"CereProc" voices are broken in this site.

### ISSUE THREAD

**Issue by thetoonsofjosh** [chrisjp/tts#22]
I'm making this issue because yesterday, the voices from CereProc happened to stopped working, but the site now has it working again,  https://www.cereproc.com/ but not in this site, every voice I use from that api results in a "input data format error", Did CereProc changed their api or something? Is there anything you can do Chris?

**Comment by chrisjp** [comment]
Thanks for reporting. Just had a look at their demo site and it looks like there was a minor upgrade to their website software. The demo key has changed and the name of the cookie has changed too. Very simple fix. Should have some time to get this fixed on the website by the end of today. Will update here once it's done.

**Comment by chrisjp** [comment]
My website has now been updated with the fix. Thanks again for reporting this.
