### ISSUE TITLE
Streamlabs Polly voices now require a new header

### ISSUE THREAD

**Issue by HappyMac3920** [chrisjp/tts#35]
Streamlabs changed how Polly speech is requested.
Now, **it requires a referer in the header**, but the request is still simple:
```
curl 'https://streamlabs.com/polly/speak' \
  -H 'referer: https://streamlabs.com' \
  --data-raw 'text=This+is+a+test+donation+for+%2416.00.&voice=Brian'
```

**Comment by chrisjp** [comment]
Tested and it works locally. Thanks for that. Will push the fix now.

**Comment by HappyMac3920** [comment]
> Tested and it works locally. Thanks for that. Will push the fix now.

Alright, it works now.
Looking forward to the MS Edge voices. :)
