### ISSUE TITLE
TikTok, ReadSpeaker, and iSpeech TTS don't work, errors given for the first two.

### ISSUE THREAD

**Issue by 5ucur** [chrisjp/tts#4]
TikTok throws `Error: Couldn't load speech. Try again.`
ReadSpeaker throws `Error: Unknown error.`
iSpeech outputs no error but also no sound.

Tested on the latest Firefox on Arch Linux and Windows 7, same results on both machines.

**Comment by chrisjp** [comment]
Thanks for reporting, I know it was a long time ago but I'll see if I can keep up with actively maintaining this again.

About those errors:
* TikTok - this should be fixable. Needs a valid session ID from cookie after logging in, which unfortunately only lasts for 30 days. Doing this programmatically every 30 days *might* be possible - not really within the scope of the project - but I'll see if there's a better solution for keeping these voices available permanently.
* ReadSpeaker - they've moved their voice demo behind a paywall and the old API URLs all 404 now. Highly unlikely we'll ever be able to freely access these again so they will be removed from this.
* iSpeech - their [own demo site](https://www.ispeech.org/text.to.speech) isn't working for me at the time of posting this comment. I don't know how long it's been broken for but if it has been a long time then I suspect they removed the demo voices - if that's the case they'll be removed from here too as we'll have no way to use them.
